### ISSUE TITLE
Travis-CI build fails due to missing packages

### ISSUE THREAD

**Issue by eddex** [HSLU-BaumannWicki/BA-Dokumentation-Template#1]
Hi

Fist of all, thanks for the awesome template! I'll write my BDA this semester and I'm gonna use it. Unfortunately I cannot make the documentation public on GitHub so I'm using a private repo.

While setting up travis-ci, I encountered some build errors:
![image](https://user-images.githubusercontent.com/5302085/74773948-243eff80-5293-11ea-9970-d597b9523fcf.png)

They were all caused by missing `tlmgr` packages. Travis caches the previously installed packages, maybe that's why the build works on your environment.

The missing packages are:
- bitset
- letltxmacro
- pdfescape
- pdflscape
- ragged2e

**Comment by KilnOfTheSecondFlame** [comment]
Thanks for the flowers 😄 Me and @CryDeb are happy that our work is still useful =)
Huh, could be that these packages were dependencies before and got installed too. The cache shouldn't have been a problem back then.

Thanks for the fix! A little caveat though:
The packages for the specific distro get installed in .travis.yml, as we wanted the minimal install to be generic. Could you move the `tlmgr install` to the correct file?

**Comment by eddex** [comment]
I moved the install of the missing packages to `.travis.yml`, should be consistent with the rest now: https://github.com/HSLU-BaumannWicki/BA-Dokumentation-Template/pull/2/commits/191753b4a3313cf3466ebacd1bab7bf3263a5c00

**Comment by KilnOfTheSecondFlame** [comment]
Thanks for the fix =)
