### ISSUE TITLE
Question about "Eulenskript"

### ISSUE THREAD

**Issue by Fenix4k** [HSLU-BaumannWicki/BA-Dokumentation-Template#7]
hey there

sorry to bother you with an issue, but I cannot contact you anyway else.

I am currently studying at HSLU as well and I wanted to ask which version of the "Eulenskript" was your guideline for this TeX-template?

thanks for your work and best regards, Silvan

**Comment by KilnOfTheSecondFlame** [comment]
This was not based on the EulenSkript iirc, but on the Word template they handed out at the beginning of our course

**Comment by Fenix4k** [comment]
hey there

thanks for the answer - we didnt get a template anymore but it will work

thanks and best regards, Silvan

**Comment by KilnOfTheSecondFlame** [comment]
That is nice to hear, please feel free to fork/make a merge request with an updated template if the requirements became more stringent / something was added.
May our template help a lot of HSLU BSc students =)
